name: NITM release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      KEY_ALIAS: ${{ secrets.NITM_KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.NITM_KEY_PASSWORD }}
      STORE_PASSWORD: ${{ secrets.NITM_STORE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.7.1"
          cache: true

      - name: Write file
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: public_key.jks
          fileDir: ./android/
          encodedString: ${{ secrets.SIGNINGKEYBASE64 }}

      - run: flutter --version
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - run: flutter build appbundle

      - name: Generate checksum
        run: |
          cd build/app/outputs/apk/release/
          for file in *; do hash=$(sha256sum "$file" | cut -d' ' -f1); echo ${hash} > "${hash}_${file%.*}.sha256"; done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ contains(github.ref_name, 'alpha') || contains(github.ref_name, 'beta') }}
          files: |
            checksum.txt
            build/app/outputs/bundle/release/*.aab
            build/app/outputs/apk/release/*
